#!/bin/bash

cp kb-symbols/* /usr/share/X11/xkb/symbols
cp kb-rules/* /usr/share/X11/xkb/rules
cp keyboard /etc/default/keyboard
cp karabiner.json ~/.config/karabiner
cp .spacemacs ~/
cp .tmux.conf ~/

echo "export VISUAL=vim" >> ~/.bashrc
echo "export EDITOR=\"\$VISUAL\"" >> ~/.bashrc

if ! git config --global user.name > /dev/null; then
	git config --global user.name "Tarjei Skjærset"
fi

if ! git config --global user.email > /dev/null; then
	git config --global user.email "epost@tarjei.org"
fi
